IDM-SP-2021/afiye

src/routes/account.js
Register page reload missing title attribute which caused page reload to fail upon invalid register form submission
=> Fix register crash on invalid form suubmission

package-lock.json, package.json, src/js/app.js, src/js/tree.js, src/routes/account.js, src/scss/foundation/_normalize.scss, src/scss/foundation/_variables.scss, src/scss/partials/_base.scss, src/scss/partials/_footer.scss, src/scss/partials/_header.scss, src/scss/partials/_mobile-nav.scss, src/scss/styles.scss, src/server/neo4j.js, src/server/server-dev.js, src/server/server-prod.js, src/views/feed.ejs, src/views/layout.ejs, src/views/partials/front-header.ejs, src/views/partials/user-header.ejs, src/views/partials/user-mobile-nav.ejs, src/views/profile.ejs, src/views/settings.ejs, src/views/tree.ejs, test.js, webpack/webpack.dev.js, webpack/webpack.server.js
Note: some tweaking still needs to be made to the nav elements in order for it to perfectly match the prototype but functionality is complete. We overlooked how users logout, so that needs to be prototyped before that can be finalized.
=> Add neo4j connectivity and functioning nav

src/scss/foundation/_normalize.scss, webpack/plugins.js, webpack/webpack.prod.js
correct error in webpack prod build that caused css and javascript to not load
=> Hotfix for buildProd script

src/routes/account.js, src/routes/index.js, src/server/server-dev.js, src/server/server-prod.js
Append u to start of user id and f to start of fmaily id to prevent neo4j from erroring if either id begins with a number
=> Fix production neo4j issue

src/scss/partials/_checkbox.scss, src/scss/partials/_header.scss, src/scss/partials/_settings.scss, src/scss/partials/_tree.scss, src/scss/styles.scss, src/views/partials/user-mobile-nav.ejs, src/views/settings-accessibility.ejs, src/views/settings-account-change-password.ejs, src/views/settings-account-deactivate.ejs, src/views/settings-account-leave-tree.ejs, src/views/settings-account.ejs, src/views/settings-email.ejs, src/views/settings-privacy.ejs, src/views/settings.ejs, src/views/tree-tutorial-1.ejs, src/views/tree-tutorial-2.ejs, src/views/tree-tutorial-3.ejs, src/views/tree-tutorial-4.ejs, src/views/tree-tutorial-5.ejs, src/views/tree-tutorial-6.ejs, src/views/tree.ejs
- Made all Settings screens responsive
- Made all Tree Tutorial screens responsive
- Added Nav and Header to all of these files (they were missing before)
=> Responsive Settings & Tree Tutorial

src/scss/partials/_settings.scss, src/scss/partials/_tree.scss, src/views/settings-accessibility.ejs, src/views/settings-account-change-password.ejs, src/views/settings-account-deactivate.ejs, src/views/settings-account-leave-tree.ejs, src/views/settings-account.ejs, src/views/settings-email.ejs, src/views/settings-privacy.ejs, src/views/settings.ejs, src/views/tree-tutorial-1.ejs, src/views/tree-tutorial-2.ejs, src/views/tree-tutorial-3.ejs, src/views/tree-tutorial-4.ejs, src/views/tree-tutorial-5.ejs, src/views/tree-tutorial-6.ejs
- Fixed overflow of characters of Tree Tutorial screens
- Fixed auto-width of buttons in Tree Tutorial screens
- Made Headings look bigger than paragraph text
Issues Still to be fixed
- Settings page next button placement
- minor Settings page styling issues
Co-Authored-By: Erik-Martus <43790119+Erik-Martus@users.noreply.github.com>
Co-Authored-By: Ben Murray <43625341+bam32099@users.noreply.github.com>
=> Settings and Tree Tutorial Fixes #1

src/create-album.html, src/create-profile.html
Album screen and Profile screen updated to be responsive from mobile to desktop.
=> Album & Profile Mobile-Desktop Responsive Update

src/create-memory.html
Updated breakpoints for responsive screens for Create Memory
=> Create Memory Responsive Update

src/scss/partials/_settings.scss, src/views/settings-accessibility.ejs, src/views/settings-account-change-password.ejs, src/views/settings-account-deactivate.ejs, src/views/settings-account-leave-tree.ejs, src/views/settings-account.ejs, src/views/settings-email.ejs, src/views/settings-privacy.ejs, src/views/settings.ejs
-changed to flex
-fully responsive
Co-Authored-By: Erik-Martus <43790119+Erik-Martus@users.noreply.github.com>
Co-Authored-By: Ben Murray <43625341+bam32099@users.noreply.github.com>
=> Settings Fixes

src/scss/pages/_family-confirm.scss, src/scss/partials/_button.scss, src/scss/partials/_posts.scss, src/views/feed.ejs, src/views/post.ejs, src/views/press-kit.ejs
=> Feed updates

src/scss/partials/_base.scss, src/scss/partials/_header.scss, src/scss/partials/_onboarding.scss, src/views/front/login.ejs, src/views/front/register.ejs, src/views/front/team.ejs, src/views/user/add-member.ejs
Adjusted Header, padding, and making the login/register screens more styled.
=> Add Member, Team Page, Login/Register Screen Fixes

src/scss/pages/_promo-presskit.scss, src/views/front/press-kit.ejs
Created a CSS Grid for gallery images.  Currently using placeholder imgs.
=> Promo Kit Gallery Created

src/scss/partials/_modal.scss, src/views/user/feed/feed.ejs, src/views/user/tree/tree.ejs
- fixed height on inner modal for tree tutorial
- fixed spacing issues
- fixed centered bottom text on feed screen
Co-Authored-By: Erik-Martus <43790119+Erik-Martus@users.noreply.github.com>
=> Minor Tree Tutorial Fixes

src/scss/pages/_onboarding.scss, src/scss/partials/_checkbox.scss, src/scss/partials/_register.scss, src/scss/partials/_textInput.scss, src/views/front/login.ejs, src/views/front/register.ejs, src/views/login.ejs, src/views/partials/add-user-form.ejs, src/views/register.ejs, src/views/user/member/add-member.ejs
=> Input fields update

src/scss/pages/_promo-index.scss
=> Fix functionality bugs

src/scss/partials/_base.scss, src/scss/partials/_posts.scss, src/views/user/feed/add-album.ejs, src/views/user/feed/add-post.ejs, src/views/user/feed/feed.ejs
=> Feed + Add Album + Add Post

src/scss/pages/_promo-index.scss, src/scss/pages/_promo-presskit.scss, src/scss/pages/_promo-team.scss, src/views/front/index.ejs, src/views/front/press-kit.ejs, src/views/front/team.ejs, src/views/user/settings/settings.ejs
Add links so users can report issues
=> :sparkles: Add issue report form link

src/scss/pages/_promo-index.scss, src/scss/pages/_promo-team.scss, src/views/front/index.ejs
=> :lipstick: Fix profile image stretch on mobile

src/scss/pages/_promo-team.scss, src/views/front/team.ejs
Please note, the empty file 7400 just popped up in my github and I have no idea where it is or where it comes from
=> Update Promo-Team Screen

src/views/front/index.ejs
Server is particular between .jpg and .JPG that did not cause an issue locally
=> Fix Brianna portrait not loading on home screen

src/scss/partials/_footer.scss, src/scss/partials/_textInput.scss, src/views/front/register-confirmation.ejs
Addresses issues
#155, #129, #143
=> Footer Fixes and Radio Button Restyling

src/routes/account.js, src/scss/pages/_create-profile.scss, src/scss/pages/_promo-team.scss, src/scss/partials/_button.scss, src/scss/partials/_posts.scss, src/scss/partials/_profile.scss, src/server/neo4j.js, src/views/partials/add-user-form.ejs, src/views/partials/feed-item.ejs, src/views/user/feed/album.ejs, src/views/user/feed/post.ejs, src/views/user/profile/profile.ejs
Addresses 165, 166, 167, 168, 169, 170
=> Various bug and style fixes

src/scss/partials/_base.scss, src/scss/partials/_button.scss, src/views/user/settings/settings.ejs
=> Spacing/Sizing Fixes

src/scss/partials/_family-list.scss
=> Fix tag family modal content overflow

src/scss/partials/_posts.scss
making it consistent with all other forms
@Erik-Martus @bam32099
=> Feed border radius

src/js/app.js, src/js/tree.js, src/scss/pages/_create-album.scss, src/scss/partials/_base.scss, src/scss/partials/_fullheight.scss, src/scss/partials/_graph.scss, src/scss/partials/_header.scss, src/scss/partials/_posts.scss, src/scss/partials/_profile.scss, src/scss/partials/_textInput.scss, src/views/user/feed/add-post.ejs, src/views/user/feed/edit-post.ejs
Minor issues found while testing this week.
=> Minor style updates and fixes. Add styles to file input.
